 ---------------------------------------------------------------------------------------------------------
 -----------------------------------------CREATE----TABLE-------------------------------------------------
 ---------------------------------------------------------------------------------------------------------

CREATE TABLE VOZILO (
 REG_OZNAKA VARCHAR2(20) PRIMARY KEY,
 BOJA VARCHAR2(20),
 TIP VARCHAR2(20),
 PROIZVODJAC VARCHAR2(20),
 MODEL VARCHAR2(20)
 );
 CREATE TABLE TEHNICKO_LICE (
 ID NUMBER PRIMARY KEY

 );
 CREATE TABLE POLICIJSKA_STANICA(
 ID NUMBER PRIMARY KEY,
 NAZIV VARCHAR2(30),
 OPSTINA VARCHAR2(30),
 ADRESA VARCHAR2(30),
 DATUM_OSNIVANJA DATE,
 BROJ_VOZILA NUMBER
 );---------------------------------------------------POLICAJCI
 CREATE TABLE POLICAJAC (
 ID NUMBER PRIMARY KEY,
 IME VARCHAR2(20),
 IME_RODITELJA VARCHAR2(20),
 PREZIME VARCHAR2(20),
 DATUM_RODJENJA DATE,
 JMBG CHAR(13),
 ADRESA VARCHAR2(30),
 DATUM_PRIJEMA_U_SLUZBU DATE,
 STANICA_ID NUMBER REFERENCES POLICIJSKA_STANICA(ID) NOT NULL,
 SEF_STANICE NUMBER REFERENCES POLICIJSKA_STANICA(ID),
 ZAMENIK_STANICE NUMBER REFERENCES POLICIJSKA_STANICA(ID),
 TIP VARCHAR2(50),
 CONSTRAINT JMBG_CHECK CHECK(LENGTH(JMBG) = 13)
 );
 CREATE TABLE P_ZA_VANREDNE_SITUACIJE (
 POLICAJAC_ID NUMBER PRIMARY KEY REFERENCES POLICAJAC(ID),
 KURS VARCHAR2(30),
 VESTINA VARCHAR2(30),
 DATUM_ZAVRSETKA_KURSA DATE,
 SERTIFIKAT VARCHAR2(20),
 DATUM_STICANJA_SERTIFIKATA DATE
 );
 CREATE TABLE SKOLSKI_POLICAJAC (
 POLICAJAC_ID NUMBER PRIMARY KEY REFERENCES POLICAJAC(ID),
 NAZIV_SKOLE VARCHAR2(30),
 TIP_SKOLE VARCHAR2(20),
 ADRESA_SKOLE VARCHAR2(30),
 KONTAKT_IME VARCHAR2(20),
 KONTAKT_PREZIME VARCHAR2(20),
 TELEFON_SKOLE VARCHAR2(20)
 );
 CREATE TABLE RADNIK_U_UPRAVI (
 POLICAJAC_ID NUMBER PRIMARY KEY REFERENCES POLICAJAC(ID),
 POZICIJA VARCHAR2(50)
 );
 CREATE TABLE POLICAJAC_POZORNIK (
 POLICAJAC_ID NUMBER PRIMARY KEY REFERENCES POLICAJAC(ID),
 NAZIV_ULICE VARCHAR2(30)
 );
 CREATE TABLE PATROLNI_POLICAJAC (
 POLICAJAC_ID NUMBER PRIMARY KEY REFERENCES POLICAJAC(ID),
 VRSTA_ORUZJA VARCHAR2(20)
 );
CREATE TABLE PATROLA (
 REDNI_BROJ NUMBER PRIMARY KEY,
 REG_OZNAKA_VOZILA VARCHAR2(20) REFERENCES VOZILO(REG_OZNAKA),
 POMOCNIK_ID NUMBER REFERENCES PATROLNI_POLICAJAC(POLICAJAC_ID),
 SEF_ID NUMBER REFERENCES PATROLNI_POLICAJAC(POLICAJAC_ID)
 );
 CREATE TABLE OBJEKAT (
 ID NUMBERPRIMARY KEY,
 TIP VARCHAR2(20),
 ADRESA VARCHAR2(30),
 POVRSINA NUMBER,
 KONTAKT_IME VARCHAR2(20),
 KONTAKT_PREZIME VARCHAR2(20),
 P_STANICA_ID NUMBER REFERENCES POLICIJSKA_STANICA(ID)
 );
 CREATE TABLE ALARMNI_SISTEM (
 ID NUMBERPRIMARY KEY,
 SERIJSKI_BROJ VARCHAR2(20),
 PROIZVODJAC VARCHAR2(20),
 MODELVARCHAR2(50),
 GODINA_PROIZVODNJE DATE,
 OBJEKAT_ID NUMBER REFERENCES OBJEKAT(ID),
 DATUM_INSTALACIJE DATE,
 DATUM_POSLEDNJEG_ATESTA DATE,
 DATUM_POSLEDNJEG_SERVISIRANJA DATE,
 OPIS_OTKLONJENOG_KVARA VARCHAR2(100),
 TIP VARCHAR2(50),
 HOR_REZ_IC_KAMERE NUMBER,
 VER_REZ_IC_KAMERE NUMBER,
 OSETLJIVOST VARCHAR2(20),
 GORNJA_GRANICA NUMBER,
 DONJA_GRANICA NUMBER
 );---------------------------------------------------Slabi tipovi entiteta
 CREATE TABLE UNAPREDJENJE(
 DATUM_STICANJA DATE,
 CIN VARCHAR2(50),
 POLICAJAC_ID NUMBER REFERENCES POLICAJAC(ID),
 CONSTRAINT PK_UNAPREDJENJE
 PRIMARY KEY(DATUM_STICANJA, POLICAJAC_ID)
 );------------------------------------------------------------Veze N:M
CREATE TABLE ODRZAVA(
 TEHNICAR_ID NUMBER REFERENCES TEHNICKO_LICE(ID),
 ALARMNI_SISTEM_ID NUMBER REFERENCES ALARMNI_SISTEM(ID),
 POCETNI_DATUM DATE,
 KRAJNJI_DATUM DATE,
 CONSTRAINT PK_ODRZAVA
 PRIMARY KEY (TEHNICAR_ID, ALARMNI_SISTEM_ID)
 );
 CREATE TABLE POLICIJSKA_INTERVENCIJA(
 PATROLA_ID NUMBER REFERENCES PATROLA(REDNI_BROJ),
 OBJEKAT_ID NUMBER REFERENCES OBJEKAT(ID),
 DATUM_I_VREME DATE,
 OPIS VARCHAR2(50),
 CONSTRAINT PK_INTERVENCIJA
 PRIMARY KEY(PATROLA_ID, OBJEKAT_ID)
 );-----------------------------------------------------------Visevrednosni atributi
 CREATE TABLE BROJ_TELEFONA(
 BROJ VARCHAR2(20),
 OBJEKAT_ID NUMBER REFERENCES OBJEKAT(ID),
 CONSTRAINT PK_BROJ_TELEFONA
 PRIMARY KEY (BROJ, OBJEKAT_ID)
 );
 CREATE TABLE OBRAZOVANJE (
 SKOLA VARCHAR2(50),
 DATUM_DIPLOMIRANJA DATE,
 POLICAJAC_ID NUMBER REFERENCES POLICAJAC(ID),
 CONSTRAINT PK_OBRAZOVANJE
 PRIMARY KEY (SKOLA, DATUM_DIPLOMIRANJA, POLICAJAC_ID)
 );

 ---------------------------------------------------------------------------------------------------------
 -----------------------------------------ALTER----TABLE--------------------------------------------------
 ---------------------------------------------------------------------------------------------------------

 ALTER TABLE "POLICAJAC" ADD CONSTRAINT "POLICAJAC_TIP_CHK" 
 CHECK (TIP IN ('PATROLNI POLICAJAC','POLICAJAC ZA VANREDNE SITUACIJE', 'SKOLSKI POLICAJAC', 'RADNIK U UPRAVI', 'POLICAJAC POZORNIK')) ENABLE;

ALTER TABLE "ALARMNI_SISTEM" ADD CONSTRAINT "ALARMNI_SISTEM_TIP_CHK" 
CHECK (TIP IN ('ULTRAZVUCNI','DETEKCIJEA POKRETA', 'DETEKCIJA TOPLOTNOG ODRAZA')) ENABLE;


---------------------------------------------------------------------------------------------------------
 --------------------------------------------SEQUENCES----------------------------------------------------
 ---------------------------------------------------------------------------------------------------------

CREATE SEQUENCE ALARMNI_SISTEM_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCACHE;

CREATE SEQUENCE OBJEKAT_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCACHE;

CREATE SEQUENCE PATROLA_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCACHE;

  CREATE SEQUENCE POLICAJAC_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCACHE;

  CREATE SEQUENCE POLICIJSKA_STANICA_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCACHE;

  CREATE SEQUENCE TEHNICKO_LICE_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCACHE;

 ---------------------------------------------------------------------------------------------------------
 --------------------------------------------TRIGERS------------------------------------------------------
 ---------------------------------------------------------------------------------------------------------


 CREATE OR REPLACE TRIGGER ALARMNI_SISTEM_TYPE_CHECK
    BEFORE INSERT ON ALARMNI_SISTEM
    FOR EACH ROW
BEGIN
    IF :NEW.TIP = 'ULTRAZVUCNI'
    THEN
        :NEW.HOR_REZ_IC_KAMERE := NULL;
        :NEW.VER_REZ_IC_KAMERE := NULL;
        :NEW.OSETLJIVOST := NULL;
    ELSE IF :NEW.TIP = 'DETEKCIJEA POKRETA'
        THEN
            :NEW.HOR_REZ_IC_KAMERE := NULL;
            :NEW.VER_REZ_IC_KAMERE := NULL;
            :NEW.GORNJA_GRANICA := NULL;
            :NEW.DONJA_GRANICA := NULL;
        ELSE IF :NEW.TIP = 'DETEKCIJA TOPLOTNOG ODRAZA'
            THEN
                :NEW.OSETLJIVOST := NULL;
                :NEW.GORNJA_GRANICA := NULL;
                :NEW.DONJA_GRANICA := NULL;
            END IF;
        END IF;
    END IF;
END;

CREATE OR REPLACE TRIGGER ALARMNI_SISTEM_AUTO_PK
    BEFORE INSERT ON ALARMNI_SISTEM
    FOR EACH ROW
BEGIN
    SELECT ALARMNI_SISTEM_ID_SEQ.NEXTVAL
    INTO :new.ID
    FROM dual;
END;

CREATE OR REPLACE TRIGGER OBJEKAT_AUTO_PK
    BEFORE INSERT ON OBJEKAT
    FOR EACH ROW
BEGIN
    SELECT OBJEKAT_ID_SEQ.NEXTVAL
    INTO :new.ID
    FROM dual;
END;

CREATE OR REPLACE TRIGGER PATROLA_AUTO_PK
    BEFORE INSERT ON PATROLA
    FOR EACH ROW
BEGIN
    SELECT PATROLA_ID_SEQ.NEXTVAL
    INTO :new.REDNI_BROJ
    FROM dual;
END;

CREATE OR REPLACE TRIGGER POLICAJAC_AUTO_PK
    BEFORE INSERT ON POLICAJAC
    FOR EACH ROW
BEGIN
    SELECT POLICAJAC_ID_SEQ.NEXTVAL
    INTO :new.ID
    FROM dual;
END;

CREATE OR REPLACE TRIGGER POLICIJSKA_STANICA_AUTO_PK
    BEFORE INSERT ON POLICIJSKA_STANICA
    FOR EACH ROW
BEGIN
    SELECT POLICIJSKA_STANICA_ID_SEQ.NEXTVAL
    INTO :new.ID
    FROM dual;
END;

CREATE OR REPLACE TRIGGER TEHNICKO_LICE_AUTO_PK
    BEFORE INSERT ON TEHNICKO_LICE
    FOR EACH ROW
BEGIN
    SELECT TEHNICKO_LICE_ID_SEQ.NEXTVAL
    INTO :new.ID
    FROM dual;
END;


 