// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Program.Main")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.Policajci.PopuniTabelu")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.picPolicajskaStanica_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUnapredjenje_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitavanjePolicajca_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.SviAlarmniSistemiForm.btnObrisiAlarmniSistem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.btnVozilo_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.picPolicajskaStanica_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.btnPolicajac_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.btnTehnickoLice_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.SvaTehnickaLicaForm.btnObrisiTehnickaLica_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.SvaTehnickaLicaForm.btnObrisiTehnickaLica_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.btnPatrole_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.UcitajPPozornikaBtn_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.btnObjekat_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.UcitajAlarmniSistemBtn_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.DataLayer.CreateSessionFactory~NHibernate.ISessionFactory")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.DTOs.DTOManager.vratiSvePolicajce~System.Collections.Generic.List{PolicijskaUprava.Entiteti.Policajac}")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnObjekti_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitaj_Skolskog_policajca_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitajPZaVanredneSituacije_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitajRadnikaUUpravi_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitajStanicu_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitajVozilo_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnUcitavanjeTehnickogLica_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.btnBrojTelefona_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.UcitajPatrolnogPolBtn_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Form1.UcitajPatroluBtn_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.PocetnaStranicaForm.btnAlarmniSistem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:PolicijskaUprava.Forme.SviAlarmniSistemiForm.PopuniTabelu")]
